/**:
  ros__parameters:
    gimbal_name: gb
    gimbal_frame_id: gb/_0/_1/_2
    gimbal_base_frame_id: gb
    gimbal_threshold: 0.1
    tf_timeout_threshold: 0.5
    # roll_range:
    #   min: -3.14 # Minimum roll angle
    #   max: 3.14 # Maximum roll angle
    # pitch_range:
    #   min: -1.57 # Minimum pitch angle
    #   max: 1.57 # Maximum pitch angle
    # yaw_range:
    #   min: -3.14 # Minimum yaw angle
    #   max: 3.14 # Maximum yaw angle